---
- name: Copy join to nodes
  copy:
    dest: /opt/kubejoin.sh
    src: ./join/kubejoin.sh
    mode: '0700'

- name: Run command on remote
  shell: /opt/kubejoin.sh



  #kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml