---
- name: Copy setup to master
  copy:
    dest: /opt/weaver.sh
    src: ./roles/k8s-setup-master/files/weaver.sh
    mode: '0700'

- name: Run command on remote
  become: yes
  shell: /opt/weaver.sh
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Create Kubernetes config directory
  file:
    path: ".kube/"
    state: directory

- name: Copy admin.conf to Home directory
  become: yes
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: ".kube/config"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755
    remote_src: true