- name: Ensure Weave Daemonset is Configured
  become: yes
  command: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
  register: weave_result
  ignore_errors: yes

- name: Check Weave Daemonset Status
  command: kubectl get daemonset -n kube-system weave-net -o json
  ignore_errors: yes
  register: daemonset_status

- name: Retry Daemonset Apply if Failed
  command: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
  when: "'Error' in daemonset_status.stdout or 'DaemonSet does not have minimum availability' in daemonset_status.stderr"
  retries: 3
  delay: 10
  until: false
