---
- name: Install docker prerequisites
  apt:
    update_cache: yes
    name: "{{ item }}"
  loop: "{{ docker_prereqs_packages }}"

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: Install Docker
  apt:
    name: "{{ item }}"
  loop: "{{ docker_packages }}"

- name: Giving privileges to docker.sock
  become: yes
  file:
    path: /var/run/docker.sock
    mode: '0666'