#- name: Install k8s and docker packages
#  become: yes
#  vars:
#    ansible_user: ubuntu
#    ansible_ssh_private_key_file: ~/.ssh/eli_k8s.pem
#  hosts: ec2 #It applies to all created EC2.
#  roles:
#    - docker
#    - k8s-all

#- name: Setup master node
#  become: yes
#  vars:
#    ansible_user: ubuntu
#    ansible_ssh_private_key_file: ~/.ssh/eli_k8s.pem  
#  hosts: tag_Type_master
#  roles:
#    - k8s-master

#- name: Setup worker node
#  become: yes
#  vars:
#    ansible_user: ubuntu
#    ansible_ssh_private_key_file: ~/.ssh/eli_k8s.pem
#  hosts: tag_Type_worker
#  roles:
#    - k8s-worker

- name: Setup master node
  become: yes
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/eli_k8s.pem
  hosts: tag_Type_master
  roles:
    - k8s-setup-master