- name: Destroy cluster before starting again
  command: kubeadm reset -f

- name: Initialize k8s cluster
  become: yes
  command: kubeadm init
  register: kubeadm_init_output

- name: Create file with output
  copy:
    content: "{{ kubeadm_init_output.stdout }}"
    dest: /root/kubeadminit

- name: Prepare kubejoin script
  shell: tail -2 /root/kubeadminit > /root/kubejoin.sh

- name: Get kubejoin
  fetch:
    dest: ./join
    src: /root/kubejoin.sh

- name: Organize files
  shell: |
        cp join/{{ inventory_hostname }}/root/kubejoin.sh join/  
        rm -fr join/{{ inventory_hostname }}
  delegate_to: localhost
  become: no
        
- name: Install pod network
  command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Create Kubernetes config directory
  file:
    path: ".kube/"
    state: directory

- name: Copy admin.conf to Home directory
  become: yes
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: ".kube/config"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755
    remote_src: true